package gott

type NumberFormatInfo struct {

	//The number of decimal places to use in currency values
	//CurrencyDecimalDigits = 2: $1,234.00
	//CurrencyDecimalDigits = 4: $1,234.0000
	CurrencyDecimalDigits int32

	//The string to use as the decimal separator in currency values
	//CurrencyDecimalSeparator = ".";  $123,456,789.00
	//CurrencyDecimalSeparator = " "; $123,456,789 00
	CurrencyDecimalSeparator string

	//The string that separates groups of digits to the left of the decimal in currency values
	//CurrencyDecimalSeparator = ",";  $123,456,789.00
	//CurrencyDecimalSeparator = " "; $123 456 789.00
	CurrencyGroupSeparator string

	//The number of digits in each group to the left of the decimal in currency values
	//CurrencyGroupSizes = []{ 3, 4, 5 }; $55,55555,55555,55555,4444,333.00
	//CurrencyGroupSizes = []{ 3, 4, 0 }; $55555555555555555,4444,333.00
	CurrencyGroupSizes []int32

	//The format pattern for negative currency
	//0	($n)
	//1	-$n
	//2	$-n
	//3	$n-
	//4	(n$)
	//5	-n$
	//6	n-$
	//7	n$-
	//8	-n $
	//9	-$ n
	//10	n $-
	//11	$ n-
	//12	$ -n
	//13	n- $
	//14	($ n)
	//15	(n $)
	CurrencyNegativePattern int32

	//0	$n
	//1	n$
	//2	$ n
	//3	n $
	CurrencyPositivePattern int32

	//The string to use as the currency symbol
	//CurrencySymbol="$"; $106.25
	CurrencySymbol string

	//The string that represents negative infinity.
	//-Infinity
	NegativeInfinitySymbol string

	//The string that denotes that the associated number is negative
	NegativeSign string

	//The number of decimal places to use in numeric values
	//NumberDecimalDigits=2; -1,234.00
	//NumberDecimalDigits=4; -1,234.0000
	NumberDecimalDigits int32

	//the number decimal separator
	NumberDecimalSeparator string

	//The string that separates groups of digits to the left of the decimal in numeric values
	//NumberGroupSeparator = ","; 123,456,789.00
	//NumberGroupSeparator = " "; 123 456 789.00
	NumberGroupSeparator string

	//The number of digits in each group to the left of the decimal in numeric values
	//NumberGroupSizes = []{ 3, 4, 5 }; $55,55555,55555,55555,4444,333.00
	//NumberGroupSizes = []{ 3, 4, 0 }; $55555555555555555,4444,333.00
	NumberGroupSizes []int32

	//The format pattern for negative numeric values
	//       Default:             -1,234.00
	//       Pattern 0:           (1,234.00)
	//       Pattern 1:           -1,234.00
	//       Pattern 2:           - 1,234.00
	//       Pattern 3:           1,234.00-
	//       Pattern 4:           1,234.00 -
	NumberNegativePattern int32

	//The number of decimal places to use in percent values
	//PercentDecimalDigits = 2; 12.34 %
	//PercentDecimalDigits = 4; 12.3400 %
	PercentDecimalDigits int32

	//The string to use as the decimal separator in percent values
	//12.34 %
	//12 34 %
	PercentDecimalSeparator string

	//The string that separates groups of digits to the left of the decimal in percent values
	//PercentGroupSeparator= ",";  123,456.78 %
	//PercentGroupSeparator= " "; 123 456.78 %
	PercentGroupSeparator string

	//The number of digits in each group to the left of the decimal in percent values
	//PercentGroupSizes = { 3, 4, 5 }; 55,55555,55555,55555,4444,333.00%
	//PercentGroupSizes = { 3, 4, 0 }; 55555555555555555,4444,333.00%
	//{2,3,0}; 123456789012,346,00.00 %
	//{2,3,4}; 1234,5678,9012,346,00.00 %
	PercentGroupSizes []int32

	//0	-n %
	//1	-n%
	//2	-%n
	//3	%-n
	//4	%n-
	//5	n-%
	//6	n%-
	//7	-% n
	//8	n %-
	//9	% n-
	//10	% -n
	//11	n- %
	PercentNegativePattern int32

	//0	n %
	//1	n%
	//2	%n
	//3	% n
	PercentPositivePattern int32

	//The string to use as the percent symbol.
	PercentSymbol string

	//The string to use as the per mille symbol "‰" (U+2030)
	PerMilleSymbol string

	//The string that represents positive infinity, "Infinity"
	PositiveInfinitySymbol string

	//The string that denotes that the associated number is positive
	PositiveSign string
}


var numberFormats = map[string]NumberFormatInfo {
	"ar-SA": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "ر.س.‏",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 0,PercentPositivePattern: 0,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"eu-ES": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: ".",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "€",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: ".",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: ".",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 7,PercentPositivePattern: 3,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"el-GR": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: ".",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "€",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: ".",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: ".",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"fo-FO": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: ".",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "kr",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: ".",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: ".",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 0,PercentPositivePattern: 0,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"af-ZA": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: " ",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 1,CurrencyPositivePattern: 0,CurrencySymbol: "R",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: " ",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: " ",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"sq-AL": {CurrencyDecimalDigits: 0,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: " ",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "Lekë",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: " ",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: " ",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"ar-AE": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "د.إ.‏",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"Lt-az-AZ": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: " ",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "₼",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: " ",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: " ",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 0,PercentPositivePattern: 0,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"zh-CHS": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 2,CurrencyPositivePattern: 0,CurrencySymbol: "¥",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"en-CA": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 1,CurrencyPositivePattern: 0,CurrencySymbol: "$",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"ar-IQ": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "د.ع.‏",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"ar-OM": {CurrencyDecimalDigits: 3,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "ر.ع.‏",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"ar-SY": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "ل.س.‏",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"div-MV": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 0,CurrencyPositivePattern: 0,CurrencySymbol: "ރ.",NegativeInfinitySymbol: "-Infinity",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 0,PercentPositivePattern: 0,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "Infinity",PositiveSign: "+",},
	"nl-NL": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: ".",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 12,CurrencyPositivePattern: 2,CurrencySymbol: "€",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: ".",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: ".",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"en-JM": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 1,CurrencyPositivePattern: 0,CurrencySymbol: "$",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"ar-BH": {CurrencyDecimalDigits: 3,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "د.ب.‏",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"ar-YE": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "ر.ي.‏",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"en-PH": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 1,CurrencyPositivePattern: 0,CurrencySymbol: "₱",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"en-BZ": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 1,CurrencyPositivePattern: 0,CurrencySymbol: "$",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"en-ZW": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 1,CurrencyPositivePattern: 0,CurrencySymbol: "US$",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"fr-BE": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: ".",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "€",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: ".",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: ".",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 0,PercentPositivePattern: 0,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"fr-MC": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: " ",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "€",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: " ",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: " ",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 0,PercentPositivePattern: 0,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"de-LI": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: "’",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 9,CurrencyPositivePattern: 2,CurrencySymbol: "CHF",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: "’",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: "’",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"fr-LU": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: ".",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "€",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: ".",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: ".",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 0,PercentPositivePattern: 0,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"ar-EG": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "ج.م.‏",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"hy-AM": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "֏",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"be-BY": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: " ",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "Br",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: " ",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: " ",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 0,PercentPositivePattern: 0,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"da-DK": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: ".",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "kr.",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: ".",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: ".",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 0,PercentPositivePattern: 0,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"en-US": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 0,CurrencyPositivePattern: 0,CurrencySymbol: "$",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"fa-IR": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: "/",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 6,CurrencyPositivePattern: 1,CurrencySymbol: "ريال",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: "/",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 3,PercentDecimalDigits: 2,PercentDecimalSeparator: "/",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 11,PercentPositivePattern: 0,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"zh-MO": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 1,CurrencyPositivePattern: 0,CurrencySymbol: "MOP",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"zh-TW": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 1,CurrencyPositivePattern: 0,CurrencySymbol: "NT$",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"fr-CA": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: " ",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 15,CurrencyPositivePattern: 3,CurrencySymbol: "$",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: " ",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: " ",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 0,PercentPositivePattern: 0,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"de-AT": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: ".",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 9,CurrencyPositivePattern: 2,CurrencySymbol: "€",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: " ",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: " ",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 0,PercentPositivePattern: 0,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"ar-LB": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "ل.ل.‏",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"zh-SG": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 1,CurrencyPositivePattern: 0,CurrencySymbol: "$",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"en-ZA": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: " ",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 1,CurrencyPositivePattern: 0,CurrencySymbol: "R",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: " ",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: " ",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"id-ID": {CurrencyDecimalDigits: 0,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: ".",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 1,CurrencyPositivePattern: 0,CurrencySymbol: "Rp",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: ".",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: ".",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"bg-BG": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: " ",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "лв.",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: " ",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: " ",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"ca-ES": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: ".",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "€",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: ".",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: ".",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"zh-CHT": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 0,CurrencyPositivePattern: 0,CurrencySymbol: "HK$",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"hr-HR": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: ".",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "kn",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: ".",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 2,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: ".",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"en-NZ": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 1,CurrencyPositivePattern: 0,CurrencySymbol: "$",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"hu-HU": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: " ",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "Ft",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: " ",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: " ",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"is-IS": {CurrencyDecimalDigits: 0,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: ".",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "kr",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: ".",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: ".",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"ar-DZ": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "د.ج.‏",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"ar-QA": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "ر.ق.‏",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"zh-HK": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 0,CurrencyPositivePattern: 0,CurrencySymbol: "HK$",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"et-EE": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: " ",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "€",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: " ",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: " ",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"gl-ES": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: ".",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "€",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: ".",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: ".",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 0,PercentPositivePattern: 0,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"he-IL": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 2,CurrencyPositivePattern: 2,CurrencySymbol: "₪",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"de-CH": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: "’",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 2,CurrencyPositivePattern: 2,CurrencySymbol: "CHF",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: "’",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: "’",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"hi-IN": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3, 2 },CurrencyNegativePattern: 12,CurrencyPositivePattern: 0,CurrencySymbol: "₹",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3, 2 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3, 2 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"ar-LY": {CurrencyDecimalDigits: 3,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "د.ل.‏",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"en-IE": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 1,CurrencyPositivePattern: 0,CurrencySymbol: "€",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"en-GB": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 1,CurrencyPositivePattern: 0,CurrencySymbol: "£",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"fi-FI": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: " ",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "€",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: " ",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: " ",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 0,PercentPositivePattern: 0,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"fr-CH": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: " ",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "CHF",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: " ",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: " ",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"ka-GE": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: " ",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "₾",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: " ",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: " ",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"ar-MA": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "د.م.‏",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"en-CB": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 0,CurrencyPositivePattern: 0,CurrencySymbol: "¤",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"de-LU": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: ".",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "€",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: ".",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: ".",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 0,PercentPositivePattern: 0,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"gu-IN": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3, 2 },CurrencyNegativePattern: 12,CurrencyPositivePattern: 0,CurrencySymbol: "₹",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3, 2 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3, 2 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"zh-CN": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 2,CurrencyPositivePattern: 0,CurrencySymbol: "¥",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"de-DE": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: ".",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "€",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: ".",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: ".",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 0,PercentPositivePattern: 0,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"ar-KW": {CurrencyDecimalDigits: 3,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "د.ك.‏",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"en-AU": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 1,CurrencyPositivePattern: 0,CurrencySymbol: "$",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"en-TT": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 1,CurrencyPositivePattern: 0,CurrencySymbol: "$",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"fr-FR": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: " ",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "€",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: " ",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: " ",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 0,PercentPositivePattern: 0,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"ar-JO": {CurrencyDecimalDigits: 3,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "د.ا.‏",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"ar-TN": {CurrencyDecimalDigits: 3,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "د.ت.‏",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"Cy-az-AZ": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 1,CurrencyPositivePattern: 0,CurrencySymbol: "₼",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"cs-CZ": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: " ",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "Kč",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: " ",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: " ",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 0,PercentPositivePattern: 0,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"nl-BE": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ",",CurrencyGroupSeparator: ".",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 8,CurrencyPositivePattern: 3,CurrencySymbol: "€",NegativeInfinitySymbol: "-∞",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ",",NumberGroupSeparator: ".",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ",",PercentGroupSeparator: ".",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "∞",PositiveSign: "+",},
	"default": {CurrencyDecimalDigits: 2,CurrencyDecimalSeparator: ".",CurrencyGroupSeparator: ",",CurrencyGroupSizes: []int32{ 3 },CurrencyNegativePattern: 0,CurrencyPositivePattern: 0,CurrencySymbol: "¤",NegativeInfinitySymbol: "-Infinity",NegativeSign: "-",NumberDecimalDigits: 2,NumberDecimalSeparator: ".",NumberGroupSeparator: ",",NumberGroupSizes: []int32{ 3 },NumberNegativePattern: 1,PercentDecimalDigits: 2,PercentDecimalSeparator: ".",PercentGroupSeparator: ",",PercentGroupSizes: []int32{ 3 },PercentNegativePattern: 1,PercentPositivePattern: 1,PercentSymbol: "%",PerMilleSymbol: "‰",PositiveInfinitySymbol: "Infinity",PositiveSign: "+",},
}